#!/usr/bin/env bash
# Regenerate config/team-catalog.json from live league APIs.
# Run this locally (sandbox blocks the upstream hosts).
#
# Sources:
#   MLB:        https://statsapi.mlb.com/api/v1/teams?sportId=1&activeStatus=Y
#   NFL/NBA/NHL: https://site.api.espn.com/apis/site/v2/sports/{sport}/teams (paginated)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$SCRIPT_DIR"

OUT="config/team-catalog.json"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

echo "Fetching MLB teams..." >&2
mlb="$(curl -fsSL --max-time 15 'https://statsapi.mlb.com/api/v1/teams?sportId=1&activeStatus=Y' \
  | jq '[ .teams[] | { name, abbrev: .abbreviation, id, aliases: [ .teamName, .name ] | map(ascii_downcase | gsub("[^a-z0-9 ]"; "")) | unique } ] | sort_by(.name)')"

fetch_espn() {
  local sport="$1"
  curl -fsSL --max-time 15 "https://site.api.espn.com/apis/site/v2/sports/$sport/teams?limit=100" \
    | jq '[ .sports[0].leagues[0].teams[].team |
            { name: .displayName, abbrev: .abbreviation, id: (.id|tonumber? // .id), aliases: [ .nickname, .shortDisplayName, .name ] | map(ascii_downcase) | unique } ] | sort_by(.name)'
}

echo "Fetching NFL teams..." >&2
nfl="$(fetch_espn football/nfl)"
echo "Fetching NBA teams..." >&2
nba="$(fetch_espn basketball/nba)"
echo "Fetching NHL teams..." >&2
nhl="$(fetch_espn hockey/nhl)"

jq -n --argjson mlb "$mlb" --argjson nfl "$nfl" --argjson nba "$nba" --argjson nhl "$nhl" '
  { _comment: "Generated by scripts/build-catalog.sh", mlb: $mlb, nfl: $nfl, nba: $nba, nhl: $nhl }
' > "$TMP"

mv "$TMP" "$OUT"
echo "Wrote $OUT:" >&2
jq '[.mlb,.nfl,.nba,.nhl] | map(length)' "$OUT" >&2
