#!/usr/bin/env bash
# scripts/build-catalog.sh — regenerate config/team-catalog.json from live
# league APIs. Run locally; the sandbox firewalls block the upstream hosts.
#
# Sources:
#   MLB:         https://statsapi.mlb.com/api/v1/teams?sportId=1&activeStatus=Y
#   NFL/NBA/NHL: https://site.api.espn.com/apis/site/v2/sports/{sport}/teams
#
# All fetches go through safe_curl, so the same hostname allow-list,
# HTTPS-only enforcement, and 5 MB size cap that protect the runtime
# helpers also protect this regenerator.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$SCRIPT_DIR"

# shellcheck source=scripts/_lib.sh
. "$SCRIPT_DIR/scripts/_lib.sh"

OUT="config/team-catalog.json"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

# Fetch MLB once, then transform: keep only the fields we care about, build
# an alias list from the team's nickname + full name, lower-case and strip
# anything that isn't [a-z0-9 ] so the catalog only ever holds safe lookup
# strings (matches the validator allow-list in _lib.sh).
echo "Fetching MLB teams..." >&2
mlb="$(safe_curl 'https://statsapi.mlb.com/api/v1/teams?sportId=1&activeStatus=Y' \
  | jq '[ .teams[] |
          { name,
            abbrev: .abbreviation,
            id,
            aliases: [ .teamName, .name ] | map(ascii_downcase | gsub("[^a-z0-9 ]"; "")) | unique
          }
        ] | sort_by(.name)')"

# ESPN's /teams endpoint paginates after 25 entries; we ask for 100 to
# guarantee a single response covers the whole league.
fetch_espn() {
  local sport="$1"
  safe_curl "https://site.api.espn.com/apis/site/v2/sports/$sport/teams?limit=100" \
    | jq '[ .sports[0].leagues[0].teams[].team |
            { name: .displayName,
              abbrev: .abbreviation,
              id: (.id|tonumber? // .id),
              aliases: [ .nickname, .shortDisplayName, .name ] | map(ascii_downcase) | unique
            }
          ] | sort_by(.name)'
}

echo "Fetching NFL teams..." >&2
nfl="$(fetch_espn football/nfl)"
echo "Fetching NBA teams..." >&2
nba="$(fetch_espn basketball/nba)"
echo "Fetching NHL teams..." >&2
nhl="$(fetch_espn hockey/nhl)"

jq -n --argjson mlb "$mlb" --argjson nfl "$nfl" --argjson nba "$nba" --argjson nhl "$nhl" '
  { _comment: "Generated by scripts/build-catalog.sh", mlb: $mlb, nfl: $nfl, nba: $nba, nhl: $nhl }
' > "$TMP"

# Run the integrity check against the freshly-generated file before
# overwriting the committed one. If a future API change breaks the shape
# we expect, fail loudly here instead of leaving a broken catalog in tree.
if ! assert_catalog_sane "$TMP"; then
  echo "generated catalog failed integrity check; aborting" >&2
  exit 2
fi

mv "$TMP" "$OUT"
echo "Wrote $OUT:" >&2
jq '[.mlb,.nfl,.nba,.nhl] | map(length)' "$OUT" >&2
